/* THIS IS AN AUTOMATICALLY GENERATED FILE
   IF YOU MODIFY THIS BY HAND BE PREPARED!
   TO HAVE YOUR CHANGES OVERWRITTEN */
package org.wikipedia.staticdata;

import android.support.annotation.NonNull;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public final class MainPageNameData {
    @NonNull private static final Map<String, String> DATA_MAP = Collections.unmodifiableMap(newMap());

    @NonNull public static String valueFor(String key) {
        if (DATA_MAP.containsKey(key)) {
            return DATA_MAP.get(key);
        }
        return DATA_MAP.get("en");
    }

    @SuppressWarnings({"checkstyle:methodlength", "SpellCheckingInspection"})
    private static Map<String, String> newMap() {
        final int size = 294;
        Map<String, String> map = new HashMap<>(size);
        map.put("ab", "Ихадоу адаҟьа");
        map.put("ace", "Ôn Keuë");
        map.put("ady", "НэкӀубгъо шъхьаӀ");
        map.put("af", "Tuisblad");
        map.put("ak", "Krataafa Titiriw");
        map.put("als", "Wikipedia:Houptsyte");
        map.put("am", "ዋናው ገጽ");
        map.put("an", "Portalada");
        map.put("ang", "Hēafodtramet");
        map.put("ar", "الصفحة الرئيسية");
        map.put("arc", "ܦܐܬܐ ܪܝܫܝܬܐ");
        map.put("arz", "الصفحه الرئيسيه");
        map.put("as", "বেটুপাত");
        map.put("ast", "Portada");
        map.put("atj", "Otitikowin");
        map.put("av", "БетӀераб гьумер");
        map.put("ay", "Nayriri uñstawi");
        map.put("az", "Ana Səhifə");
        map.put("azb", "آنا صفحه");
        map.put("ba", "Баш бит");
        map.put("bar", "Hoamseitn");
        map.put("bat-smg", "Pėrms poslapis");
        map.put("bcl", "Panginot na Pahina");
        map.put("be", "Галоўная старонка");
        map.put("be-x-old", "Галоўная старонка");
        map.put("bg", "Начална страница");
        map.put("bh", "मुख्य पन्ना");
        map.put("bi", "Nambawan Pej");
        map.put("bjn", "Tungkaran Tatambaian");
        map.put("bm", "Nyɛ fɔlɔ");
        map.put("bn", "প্রধান পাতা");
        map.put("bo", "གཙོ་ངོས།");
        map.put("bpy", "পয়লা পাতা");
        map.put("br", "Degemer");
        map.put("bs", "Početna strana");
        map.put("bug", "Mappadecéŋ");
        map.put("bxr", "Нюур хуудаһан");
        map.put("ca", "Portada");
        map.put("cbk-zam", "El Primero Pagina");
        map.put("cdo", "Tàu Hiĕk");
        map.put("ce", "Коьрта агӀо");
        map.put("ceb", "Unang Panid");
        map.put("ch", "Fanhaluman");
        map.put("chr", "ᎤᎵᎮᎵᏍᏗ");
        map.put("chy", "Va'ohtama");
        map.put("ckb", "دەستپێک");
        map.put("co", "Pagina maestra");
        map.put("cr", "ᓃᔥᑕᒻᐹᔅᑌᒋᓂᑲᓐ");
        map.put("crh", "Baş Saife");
        map.put("cs", "Hlavní strana");
        map.put("csb", "Przédnô starna");
        map.put("cu", "Главьна страница");
        map.put("cv", "Тĕп страницă");
        map.put("cy", "Hafan");
        map.put("da", "Forside");
        map.put("de", "Wikipedia:Hauptseite");
        map.put("din", "Apam këdït");
        map.put("diq", "Perra Seri");
        map.put("dsb", "Głowny bok");
        map.put("dty", "मुख्य पन्ना");
        map.put("dv", "މައި ޞަފްޙާ");
        map.put("dz", "མ་ཤོག།");
        map.put("ee", "Axa do Ŋgɔ");
        map.put("el", "Πύλη:Κύρια");
        map.put("eml", "PP");
        map.put("en", "Main Page");
        map.put("eo", "Vikipedio:Ĉefpaĝo");
        map.put("es", "Wikipedia:Portada");
        map.put("et", "Esileht");
        map.put("eu", "Azala");
        map.put("ext", "Página prencipal");
        map.put("fa", "صفحهٔ اصلی");
        map.put("ff", "Hello jaɓɓorgo");
        map.put("fi", "Wikipedia:Etusivu");
        map.put("fiu-vro", "Pääleht");
        map.put("fj", "Tabana levu");
        map.put("fo", "Forsíða");
        map.put("fr", "Wikipédia:Accueil principal");
        map.put("frp", "Vouiquipèdia:Reçua principâla");
        map.put("frr", "Wikipedia:Hoodsid");
        map.put("fur", "Pagjine principâl");
        map.put("fy", "Haadside");
        map.put("ga", "Príomhleathanach");
        map.put("gag", "Baş yaprak");
        map.put("gan", "封面");
        map.put("gd", "Prìomh-Dhuilleag");
        map.put("gl", "Portada");
        map.put("glk", "گتˇ ولگ");
        map.put("gn", "Ape");
        map.put("gom", "मुखेल पान");
        map.put("gor", "Halaman Bungaliyo");
        map.put("gu", "મુખપૃષ્ઠ");
        map.put("gv", "Ard-ghuillag");
        map.put("ha", "Babban shafi");
        map.put("hak", "Thèu-Ya̍p");
        map.put("haw", "Ka papa kinohi");
        map.put("he", "עמוד ראשי");
        map.put("hi", "मुखपृष्ठ");
        map.put("hif", "Pahila Panna");
        map.put("hr", "Glavna stranica");
        map.put("hsb", "Hłowna strona");
        map.put("ht", "Paj Prensipal");
        map.put("hu", "Kezdőlap");
        map.put("hy", "Գլխավոր էջ");
        map.put("ia", "Pagina principal");
        map.put("id", "Halaman Utama");
        map.put("ie", "Principal págine");
        map.put("ig", "Ihu m̀bụ");
        map.put("ik", "Makpiġaaq Kanna");
        map.put("ilo", "Umuna a Panid");
        map.put("inh", "Керттера оагӀув");
        map.put("io", "Frontispico");
        map.put("is", "Forsíða");
        map.put("it", "Pagina principale");
        map.put("iu", "ᐊᒥᖅ");
        map.put("ja", "メインページ");
        map.put("jam", "Mien Piej");
        map.put("jbo", "uikipedi'as:ralju");
        map.put("jv", "Tepas");
        map.put("ka", "მთავარი გვერდი");
        map.put("kaa", "Bas bet");
        map.put("kab", "Asebtar amenzu");
        map.put("kbd", "НапэкӀуэцӀ нэхъыщхьэ");
        map.put("kbp", "Talɩ ɖeu");
        map.put("kg", "Mukânda ya ngudi");
        map.put("ki", "Main Page");
        map.put("kk", "Басты бет");
        map.put("kl", "Saqqaa");
        map.put("km", "ទំព័រដើម");
        map.put("kn", "ಮುಖ್ಯ ಪುಟ");
        map.put("ko", "위키백과:대문");
        map.put("koi", "Пондӧтчан листбок");
        map.put("krc", "Баш бет");
        map.put("ks", "اہم صَفہٕ");
        map.put("ksh", "Wikipedia:Houpsigk");
        map.put("ku", "Destpêk");
        map.put("kv", "Медшӧр лист бок");
        map.put("kw", "Folen dre");
        map.put("ky", "Башбарак");
        map.put("la", "Vicipaedia:Pagina prima");
        map.put("lad", "La Primera Hoja");
        map.put("lb", "Haaptsäit");
        map.put("lbe", "Агьаммур лажин");
        map.put("lez", "Кьилин ччин");
        map.put("lfn", "Paje xef");
        map.put("lg", "Olupapula Olusooka");
        map.put("li", "Veurblaad");
        map.put("lij", "Pagina prinçipâ");
        map.put("lmo", "Pagina principala");
        map.put("ln", "Lokásá ya libosó");
        map.put("lo", "ໜ້າຫຼັກ");
        map.put("lrc", "سرآسۊنٱ");
        map.put("lt", "Pagrindinis puslapis");
        map.put("ltg", "Suoku puslopa");
        map.put("lv", "Sākumlapa");
        map.put("mai", "सम्मुख पन्ना");
        map.put("map-bms", "Kaca Utama");
        map.put("mdf", "Пря лопа");
        map.put("mg", "Wikipedia:Fandraisana");
        map.put("mhr", "Тӱҥ лаштык");
        map.put("mi", "Hau Kāinga");
        map.put("min", "Laman Utamo");
        map.put("mk", "Главна страница");
        map.put("ml", "പ്രധാന താൾ");
        map.put("mn", "Нүүр хуудас");
        map.put("mr", "मुखपृष्ठ");
        map.put("mrj", "Тӹнг ӹлӹштӓш");
        map.put("ms", "Laman Utama");
        map.put("mt", "Il-Paġna prinċipali");
        map.put("mwl", "Biquipédia:Páigina percipal");
        map.put("my", "ဗဟိုစာမျက်နှာ");
        map.put("myv", "Прявтлопа");
        map.put("mzn", "گت صفحه");
        map.put("na", "Bwiema peij");
        map.put("nah", "Calīxatl");
        map.put("nap", "Paggena prencepale");
        map.put("nds", "Wikipedia:Hööftsiet");
        map.put("nds-nl", "Vöärblad");
        map.put("ne", "मुख्य पृष्ठ");
        map.put("new", "मू पौ");
        map.put("nl", "Hoofdpagina");
        map.put("nn", "Hovudside");
        map.put("nb", "Portal:Forside");
        map.put("nov", "Chefi pagine");
        map.put("nrm", "Page dé garde");
        map.put("nso", "Letlakala la pele");
        map.put("nv", "Íiyisíí Naaltsoos");
        map.put("ny", "Tsamba Lalikulu");
        map.put("oc", "Acuèlh");
        map.put("olo", "Piäsivu");
        map.put("om", "Fuula Dura");
        map.put("or", "ପ୍ରଧାନ ପୃଷ୍ଠା");
        map.put("os", "Сæйраг фарс");
        map.put("pa", "ਮੁੱਖ ਸਫ਼ਾ");
        map.put("pag", "Arapan ya Bolong");
        map.put("pam", "Pun Bulung");
        map.put("pap", "Página Prinsipal");
        map.put("pcd", "Accueul");
        map.put("pdc", "Haaptblatt");
        map.put("pfl", "Wikipedia:Haubdsaid");
        map.put("pi", "पमुख पत्त Pamukha patta");
        map.put("pih", "Mien Paij");
        map.put("pl", "Wikipedia:Strona główna");
        map.put("pms", "Intrada");
        map.put("pnb", "پہلا صفہ");
        map.put("pnt", "Αρχικόν σελίδα");
        map.put("ps", "لومړی مخ");
        map.put("pt", "Wikipédia:Página principal");
        map.put("qu", "Qhapaq p'anqa");
        map.put("rm", "Wikipedia:Pagina principala");
        map.put("rmy", "Sherutni patrin");
        map.put("rn", "Main Page");
        map.put("ro", "Pagina principală");
        map.put("roa-rup", "Prota frãndzã");
        map.put("roa-tara", "Pagene Prengepále");
        map.put("ru", "Заглавная страница");
        map.put("rue", "Головна сторінка");
        map.put("rw", "Intangiriro");
        map.put("sa", "मुख्यपृष्ठम्");
        map.put("sah", "Сүрүн сирэй");
        map.put("sat", "ᱢᱩᱬᱩᱛ ᱥᱟᱦᱴᱟ");
        map.put("sc", "Pàgina printzipale");
        map.put("scn", "Pàggina principali");
        map.put("sco", "Main Page");
        map.put("sd", "مُک صفحو");
        map.put("se", "Portála:Ovdasiidu");
        map.put("sg", "Gä nzönî");
        map.put("sh", "Glavna stranica");
        map.put("si", "මුල් පිටුව");
        map.put("simple", "Main Page");
        map.put("sk", "Hlavná stránka");
        map.put("sl", "Glavna stran");
        map.put("sm", "Itūlau Muamua");
        map.put("sn", "Peji Rekutanga");
        map.put("so", "Bogga Hore");
        map.put("sq", "Faqja kryesore");
        map.put("sr", "Главна страна");
        map.put("srn", "Fesipapira");
        map.put("ss", "Likhasi Lelikhulu");
        map.put("st", "Leqephe la pele");
        map.put("stq", "Haudsiede");
        map.put("su", "Tepas");
        map.put("sv", "Portal:Huvudsida");
        map.put("sw", "Mwanzo");
        map.put("szl", "Przodniŏ zajta");
        map.put("ta", "முதற் பக்கம்");
        map.put("tcy", "ಮುಖ್ಯ ಪುಟ");
        map.put("te", "మొదటి పేజీ");
        map.put("tet", "Pájina Mahuluk");
        map.put("tg", "Саҳифаи аслӣ");
        map.put("th", "หน้าหลัก");
        map.put("ti", "መበገሲ ገጽ");
        map.put("tk", "Baş Sahypa");
        map.put("tl", "Unang Pahina");
        map.put("tn", "Main Page");
        map.put("to", "Peesi tali fiefia");
        map.put("tpi", "Fran pes");
        map.put("tr", "Anasayfa");
        map.put("ts", "Tlukankulu");
        map.put("tt", "Баш бит");
        map.put("tum", "Main Page");
        map.put("tw", "Main Page");
        map.put("ty", "Fa’ari’ira’a");
        map.put("tyv", "Кол арын");
        map.put("udm", "Кутскон бам");
        map.put("ug", "ئۇيغۇرچە ۋىكىپىدىيە");
        map.put("uk", "Головна сторінка");
        map.put("ur", "صفحۂ اول");
        map.put("uz", "Bosh Sahifa");
        map.put("ve", "Hayani");
        map.put("vec", "Pajina prinsipałe");
        map.put("vep", "Pälehtpol’");
        map.put("vi", "Trang Chính");
        map.put("vls", "Voorblad");
        map.put("vo", "Cifapad");
        map.put("wa", "Mwaisse pådje");
        map.put("war", "Syahan nga Pakli");
        map.put("wo", "Xët wu njëkk");
        map.put("wuu", "封面");
        map.put("xal", "Нүр халх");
        map.put("xh", "Iphepha Elingundoqo");
        map.put("xmf", "დუდხასჷლა");
        map.put("yi", "הויפט זייט");
        map.put("yo", "Ojúewé Àkọ́kọ́");
        map.put("za", "Yiebdaeuz");
        map.put("zea", "Vòblad");
        map.put("zh", "Wikipedia:首页");
        map.put("zh-hans", "Wikipedia:首页");
        map.put("zh-hant", "Wikipedia:首页");
        map.put("zh-classical", "維基大典:卷首");
        map.put("zh-min-nan", "Thâu-ia̍h");
        map.put("zh-yue", "頭版");
        map.put("zu", "Ikhasi Elikhulu");
        map.put("test", "Main Page");
        return map;
    }

    private MainPageNameData() { }
}
