/* THIS IS AN AUTOMATICALLY GENERATED FILE
   IF YOU MODIFY THIS BY HAND BE PREPARED!
   TO HAVE YOUR CHANGES OVERWRITTEN */
package org.wikipedia.staticdata

import org.wikipedia.util.L10nUtil.getDesiredLanguageCode

object MainPageNameData {
    @JvmStatic
    fun valueFor(key: String): String {
        return dataMap[getDesiredLanguageCode(key)] ?: dataMap["en"]!!
    }

    private val dataMap = mapOf(
            "ab" to "Ихадоу адаҟьа",
            "ace" to "Ôn Keue",
            "ady" to "НэкӀубгъо шъхьаӀ",
            "af" to "Tuisblad",
            "als" to "Wikipedia:Houptsyte",
            "alt" to "Тӧс бӱк",
            "am" to "ዋናው ገጽ",
            "ami" to "Sa’ayayaw pising no tyin-naw",
            "an" to "Portalada",
            "ang" to "Heafodtramet",
            "ann" to "Uwu",
            "anp" to "मुख्य पृष्ठ",
            "ar" to "الصفحة الرئيسة",
            "arc" to "ܦܐܬܐ ܪܝܫܝܬܐ",
            "ary" to "الصفحة اللولا",
            "arz" to "الصفحه الرئيسيه",
            "as" to "বেটুপাত",
            "ast" to "Portada",
            "atj" to "Otitikowin",
            "av" to "БетӀераб гьумер",
            "avk" to "Xadola",
            "awa" to "प्रधान पन्ना",
            "ay" to "Nayriri uñstawi",
            "az" to "Ana səhifə",
            "azb" to "آنا صفحه",
            "ba" to "Баш бит",
            "ban" to "Kaca Utama",
            "bar" to "Wikipedia:Hoamseitn",
            "bat-smg" to "Pėrms poslapis",
            "bbc" to "Pogu ni Alaman",
            "bcl" to "Panginot na Pahina",
            "bdr" to "Tekokon Laman",
            "be" to "Галоўная старонка",
            "be-tarask" to "Галоўная старонка",
            "bew" to "Balé-balé",
            "bg" to "Начална страница",
            "bh" to "मुख्य पन्ना",
            "bi" to "Nambawan Pej",
            "bjn" to "Laman Tatambaian",
            "blk" to "အဓိကလိတ်မဲ့ငါ",
            "bm" to "Nyɛ fɔlɔ",
            "bn" to "প্রধান পাতা",
            "bo" to "གཙོ་ངོས།",
            "bpy" to "পয়লা পাতা",
            "br" to "Degemer",
            "bs" to "Početna strana",
            "btm" to "Alaman Utamo",
            "bug" to "Watangpola",
            "bxr" to "Нюур хуудаһан",
            "ca" to "Portada",
            "cbk-zam" to "El Primero Pagina",
            "cdo" to "Tàu Hiĕk",
            "ce" to "Коьрта агӀо",
            "ceb" to "Unang Panid",
            "ch" to "Fanhaluman",
            "chr" to "ᎤᎵᎮᎵᏍᏗ",
            "chy" to "Va'ohtama",
            "ckb" to "دەستپێک",
            "co" to "Pagina maestra",
            "crh" to "Baş Saife",
            "cs" to "Hlavní strana",
            "csb" to "Przédnô starna",
            "cu" to "Главьна страница",
            "cv" to "Тĕп страница",
            "cy" to "Hafan",
            "da" to "Forside",
            "dag" to "Solɔɣu",
            "de" to "Wikipedia:Hauptseite",
            "dga" to "A Gampɛlɛ zu",
            "din" to "Apam këdït",
            "diq" to "Pela Seri",
            "dsb" to "Głowny bok",
            "dtp" to "Natad Tagayo",
            "dty" to "मुख्य पन्ना",
            "dv" to "މައި ޞަފްޙާ",
            "dz" to "མ་ཤོག།",
            "ee" to "Axa do Ŋgɔ",
            "el" to "Πύλη:Κύρια",
            "eml" to "PP",
            "en" to "Main Page",
            "eo" to "Vikipedio:Ĉefpaĝo",
            "es" to "Wikipedia:Portada",
            "et" to "Vikipeedia:Esileht",
            "eu" to "Azala",
            "ext" to "Güiquipedia:Portá",
            "fa" to "صفحهٔ اصلی",
            "fat" to "Kratafa Tsitsir",
            "ff" to "Hello jaɓɓorgo",
            "fi" to "Wikipedia:Etusivu",
            "fiu-vro" to "Wikipedia:Pääleht",
            "fj" to "Tabana levu",
            "fo" to "Forsíða",
            "fon" to "Wémá Nukɔntɔn",
            "fr" to "Wikipédia:Accueil principal",
            "frp" to "Vouiquipèdia:Reçua principâla",
            "frr" to "Wikipedia:Hoodsid",
            "fur" to "Pagjine principâl",
            "fy" to "Haadside",
            "ga" to "Príomhleathanach",
            "gag" to "Baş yaprak",
            "gan" to "封面",
            "gcr" to "Paj Prensipal",
            "gd" to "Prìomh-Dhuilleag",
            "gl" to "Portada",
            "glk" to "گتˇ ولگ",
            "gn" to "Kuatia Ñepyrũha",
            "gom" to "मुखेल पान",
            "gor" to "Halaman Bungaliyo",
            "got" to "𐌰𐌽𐌰𐍃𐍄𐍉𐌳𐌴𐌹𐌽𐌹𐌻𐌰𐌿𐍆𐍃",
            "gpe" to "Main Page",
            "gu" to "મુખપૃષ્ઠ",
            "guc" to "Ee'iyalaaya a'laülaasü",
            "gur" to "Pɛgezure",
            "guw" to "Weda Tangan",
            "gv" to "Ard-ghuillag",
            "ha" to "Babban shafi",
            "hak" to "Thèu-Ya̍p",
            "haw" to "Ka papa kinohi",
            "he" to "עמוד ראשי",
            "hi" to "मुखपृष्ठ",
            "hif" to "Pahila Panna",
            "hr" to "Glavna stranica",
            "hsb" to "Hłowna strona",
            "ht" to "Paj Prensipal",
            "hu" to "Kezdőlap",
            "hy" to "Գլխավոր էջ",
            "hyw" to "Գլխաւոր Էջ",
            "ia" to "Pagina principal",
            "iba" to "Lambar Keterubah",
            "id" to "Halaman Utama",
            "ie" to "Principal págine",
            "ig" to "Ihu mbụ",
            "igl" to "Ogbá ogbolo",
            "ik" to "Aullaġniisaaġvik",
            "ilo" to "Umuna a Panid",
            "inh" to "Керттера оагӀув",
            "io" to "Frontispico",
            "is" to "Forsíða",
            "it" to "Pagina principale",
            "iu" to "ᐊᒥᖅ",
            "ja" to "メインページ",
            "jam" to "Mien Piej",
            "jbo" to "uikipedi'as:ralju",
            "jv" to "Wikipédia:Pendhapa",
            "ka" to "მთავარი გვერდი",
            "kaa" to "Bas bet",
            "kab" to "Asebter agejdan",
            "kai" to "Shàfi Maiwàa",
            "kaj" to "A̱gba̱dang Ka̱zzu",
            "kbd" to "НапэкӀуэцӀ нэхъыщхьэ",
            "kbp" to "Talɩ ɖeu",
            "kcg" to "A̱tsak Wat Wu",
            "kg" to "Mukânda ya ngudi",
            "kge" to "Wikipidiya:Garang",
            "ki" to "Main Page",
            "kk" to "Басты бет",
            "km" to "ទំព័រដើម",
            "kn" to "ಮುಖ್ಯ ಪುಟ",
            "knc" to "Wikipedia:Shafi kura",
            "ko" to "위키백과:대문",
            "koi" to "Пондӧтчан листбок",
            "krc" to "Баш бет",
            "ks" to "اَہَم صَفہٕ",
            "ksh" to "Wikipedia:Houpsigk",
            "ku" to "Destpêk",
            "kus" to "Zug lakir",
            "kv" to "Медшӧр лист бок",
            "kw" to "Folen dre",
            "ky" to "Башкы барак",
            "la" to "Vicipaedia:Pagina prima",
            "lad" to "La Primera Hoja",
            "lb" to "Haaptsäit",
            "lbe" to "Агьаммур лажин",
            "lez" to "Кьилин ччин",
            "lfn" to "Paje xef",
            "lg" to "Olupapula Olusooka",
            "li" to "Veurblaad",
            "lij" to "Pagina prinçipâ",
            "lld" to "Plata prinzipala",
            "lmo" to "Pagina principala",
            "ln" to "Lokásá ya libosó",
            "lo" to "ໜ້າຫຼັກ",
            "lt" to "Pagrindinis puslapis",
            "ltg" to "Suoku puslopa",
            "lv" to "Sākumlapa",
            "mad" to "Tanèyan",
            "mai" to "सम्मुख पन्ना",
            "map-bms" to "Kaca Utama",
            "mdf" to "Пря лопа",
            "mg" to "Wikipedia:Fandraisana",
            "mhr" to "Тӱҥ лаштык",
            "mi" to "Hau Kāinga",
            "min" to "Laman Utamo",
            "mk" to "Главна страница",
            "ml" to "പ്രധാന താൾ",
            "mn" to "Нүүр хуудас",
            "mni" to "ꯃꯔꯨꯑꯣꯏꯕ ꯂꯃꯥꯏ",
            "mnw" to "မုက်လိက်တမ်",
            "mos" to "Soraogo",
            "mr" to "मुखपृष्ठ",
            "mrj" to "Тӹнг ӹлӹштӓш",
            "ms" to "Laman Utama",
            "mt" to "Il-Paġna prinċipali",
            "mwl" to "Biquipédia:Páigina percipal",
            "my" to "ဗဟိုစာမျက်နှာ",
            "myv" to "Прявтлопа",
            "mzn" to "گت صفحه",
            "nah" to "Calīxatl",
            "nap" to "Paggena prencepale",
            "nds" to "Wikipedia:Hööftsiet",
            "nds-nl" to "Vöärblad",
            "ne" to "मुख्य पृष्ठ",
            "new" to "मू पौ",
            "nia" to "Wikipedia:Olayama",
            "nl" to "Hoofdpagina",
            "nn" to "Hovudside",
            "nb" to "Forside",
            "nov" to "Chefi pagine",
            "nqo" to "ߓߏ߬ߟߏ߲߬ߘߊ",
            "nr" to "Main Page",
            "nrm" to "Page dé garde",
            "nso" to "Letlakala la pele",
            "nup" to "Kpataki Kperegi",
            "nv" to "Íiyisíí Naaltsoos",
            "ny" to "Tsamba Lalikulu",
            "oc" to "Acuèlh",
            "olo" to "Piäsivu",
            "om" to "Fuula Dura",
            "or" to "ପ୍ରଧାନ ପୃଷ୍ଠା",
            "os" to "Сæйраг фарс",
            "pa" to "ਮੁੱਖ ਸਫ਼ਾ",
            "pag" to "Arapan ya Bolong",
            "pam" to "Pun Bulung",
            "pap" to "Página Prinsipal",
            "pcd" to "Accueul",
            "pcm" to "Main Pej",
            "pdc" to "Haaptblatt",
            "pfl" to "Wikipedia:Haubdsaid",
            "pi" to "पमुख पत्त Pamukha patta",
            "pl" to "Wikipedia:Strona główna",
            "pms" to "Intrada",
            "pnb" to "پہلا صفہ",
            "pnt" to "Αρχικόν σελίδα",
            "ppl" to "Achtu Amat",
            "ps" to "لومړی مخ",
            "pt" to "Wikipédia:Página principal",
            "pwn" to "sitjumaq na sapitj",
            "qu" to "Qhapaq p'anqa",
            "rki" to "အဓိကစာမျက်နှာ",
            "rm" to "Wikipedia:Pagina principala",
            "rmy" to "Sherutni patrin",
            "rn" to "Urupapuro nyamukuru",
            "ro" to "Pagina principală",
            "roa-rup" to "Prota frãndzã",
            "roa-tara" to "Pagene Prengepále",
            "rsk" to "Главни бок",
            "ru" to "Заглавная страница",
            "rue" to "Головна сторінка",
            "rw" to "Intangiriro",
            "sa" to "मुख्यपृष्ठम्",
            "sah" to "Сүрүн сирэй",
            "sat" to "ᱢᱩᱬᱩᱛ ᱥᱟᱦᱴᱟ",
            "sc" to "Pàgina printzipale",
            "scn" to "Pàggina principali",
            "sco" to "Main Page",
            "sd" to "مُک صفحو",
            "se" to "Portála:Ovdasiidu",
            "sg" to "Gä nzönî",
            "sh" to "Glavna stranica",
            "shi" to "Tasna Tamzwarut",
            "shn" to "ၼႃႈႁူဝ်ႁႅၵ်ႈ",
            "si" to "මුල් පිටුව",
            "simple" to "Main Page",
            "sk" to "Hlavná stránka",
            "skr" to "پہلا پرت",
            "sl" to "Glavna stran",
            "sm" to "Itūlau Muamua",
            "smn" to "Ovdâsijđo",
            "sn" to "Peji Rekutanga",
            "so" to "Bogga Hore",
            "sq" to "Faqja kryesore",
            "sr" to "Главна страна",
            "srn" to "Fesipapira",
            "ss" to "Likhasi Lelikhulu",
            "st" to "Leqephe la pele",
            "stq" to "Haudsiede",
            "su" to "Tepas",
            "sv" to "Portal:Huvudsida",
            "sw" to "Mwanzo",
            "syl" to "ꠝꠥꠟ ꠚꠣꠔꠣ",
            "szl" to "Przodniŏ zajta",
            "szy" to "saayaway a belih",
            "ta" to "முதற் பக்கம்",
            "tay" to "T’ringan na zzngayan",
            "tcy" to "ಮುಖ್ಯ ಪುಟ",
            "tdd" to "ᥞᥨᥝᥴ ᥘᥣᥲ ᥖᥥᥰ",
            "te" to "మొదటి పేజీ",
            "tet" to "Pájina Mahuluk",
            "tg" to "Саҳифаи аслӣ",
            "th" to "หน้าหลัก",
            "ti" to "መበገሲ ገጽ",
            "tig" to "አግዳ ገጽ",
            "tk" to "Baş Sahypa",
            "tl" to "Unang Pahina",
            "tly" to "Sərlovhə",
            "tn" to "Tsebe ya konokono",
            "to" to "Peesi tali fiefia",
            "tok" to "lipu open",
            "tpi" to "Fran pes",
            "tr" to "Anasayfa",
            "trv" to "Ruwahan patas",
            "ts" to "Tlukankulu",
            "tt" to "Баш бит",
            "tum" to "Jani likulu",
            "tw" to "Kratafa Titiriw",
            "ty" to "Fa’ari’ira’a",
            "tyv" to "Кол арын",
            "udm" to "Кутскон бам",
            "ug" to "باش بەت",
            "uk" to "Головна сторінка",
            "ur" to "صفحۂ اول",
            "uz" to "Bosh Sahifa",
            "ve" to "Hayani",
            "vec" to "Wikipedia:Prinsipio",
            "vep" to "Pälehtpol’",
            "vi" to "Trang Chính",
            "vls" to "Voorblad",
            "vo" to "Cifapad",
            "wa" to "Mwaisse pådje",
            "war" to "Syahan nga Pakli",
            "wo" to "Xët wu njëkk",
            "wuu" to "封面",
            "xal" to "Нүр халх",
            "xh" to "Iphepha Elingundoqo",
            "xmf" to "დუდხასჷლა",
            "yi" to "הויפט זייט",
            "yo" to "Ojúewé Àkọ́kọ́",
            "za" to "Yiebdaeuz",
            "zea" to "Vòblad",
            "zgh" to "ⵜⴰⵙⵏⴰ ⵏ ⵓⵙⵏⵓⴱⴳ",
            "zh" to "Wikipedia:首页",
            "zh-hans" to "Wikipedia:首页",
            "zh-hant" to "Wikipedia:首页",
            "zh-classical" to "維基大典:卷首",
            "zh-min-nan" to "Thâu-ia̍h",
            "zh-yue" to "頭版",
            "zu" to "Ikhasi Elikhulu",
            "test" to "Main Page",
            "test2" to "Main Page",
    )
}
