/* THIS IS AN AUTOMATICALLY GENERATED FILE
   IF YOU MODIFY THIS BY HAND BE PREPARED!
   TO HAVE YOUR CHANGES OVERWRITTEN */
package org.wikipedia.staticdata;

import androidx.annotation.NonNull;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public final class UserAliasData {
    @NonNull private static final Map<String, String> DATA_MAP = Collections.unmodifiableMap(newMap());

    @NonNull public static String valueFor(String key) {
        if (DATA_MAP.containsKey(key)) {
            return DATA_MAP.get(key);
        }
        return DATA_MAP.get("en");
    }

    @SuppressWarnings({"checkstyle:methodlength", "SpellCheckingInspection"})
    private static Map<String, String> newMap() {
        final int size = 306;
        Map<String, String> map = new HashMap<>(size);
        map.put("ab", "Алахәыла");
        map.put("ace", "Ureuëng Ngui");
        map.put("ady", "User");
        map.put("af", "Gebruiker");
        map.put("ak", "Odwumanyɛni");
        map.put("als", "Benutzer");
        map.put("am", "አባል");
        map.put("an", "Usuario");
        map.put("ang", "Brūcend");
        map.put("ar", "مستخدم");
        map.put("arc", "ܡܦܠܚܢܐ");
        map.put("ary", "مستخدم");
        map.put("arz", "مستخدم");
        map.put("as", "সদস্য");
        map.put("ast", "Usuariu");
        map.put("atj", "Ka notcitatc");
        map.put("av", "Участник");
        map.put("avk", "Favesik");
        map.put("awa", "यूजर");
        map.put("ay", "Usuario");
        map.put("az", "İstifadəçi");
        map.put("azb", "ایشلدن");
        map.put("ba", "Ҡатнашыусы");
        map.put("ban", "Sang Anganggé");
        map.put("bar", "Nutza");
        map.put("bat-smg", "Nauduotuos");
        map.put("bcl", "Paragamit");
        map.put("be", "Удзельнік");
        map.put("be-x-old", "Удзельнік");
        map.put("bg", "Потребител");
        map.put("bh", "प्रयोगकर्ता");
        map.put("bi", "User");
        map.put("bjn", "Pamakai");
        map.put("bm", "Utilisateur");
        map.put("bn", "ব্যবহারকারী");
        map.put("bo", "User");
        map.put("bpy", "আতাকুরা");
        map.put("br", "Implijer");
        map.put("bs", "Korisnik");
        map.put("bug", "Pengguna");
        map.put("bxr", "Хэрэглэгшэ");
        map.put("ca", "Usuari");
        map.put("cbk-zam", "Usuario");
        map.put("cdo", "用戶");
        map.put("ce", "Декъашхо");
        map.put("ceb", "Gumagamit");
        map.put("ch", "Muna'sesetbi");
        map.put("chr", "User");
        map.put("chy", "User");
        map.put("ckb", "بەکارھێنەر");
        map.put("co", "Utente");
        map.put("cr", "User");
        map.put("crh", "Qullanıcı");
        map.put("cs", "Wikipedista");
        map.put("csb", "Brëkòwnik");
        map.put("cu", "Польꙃєватєл҄ь");
        map.put("cv", "Хутшăнакан");
        map.put("cy", "Defnyddiwr");
        map.put("da", "Bruger");
        map.put("de", "Benutzer");
        map.put("din", "Dulooi");
        map.put("diq", "Karber");
        map.put("dsb", "Wužywaŕ");
        map.put("dty", "प्रयोगकर्ता");
        map.put("dv", "މެމްބަރު");
        map.put("dz", "User");
        map.put("ee", "User");
        map.put("el", "Χρήστης");
        map.put("eml", "Utente");
        map.put("en", "User");
        map.put("eo", "Uzanto");
        map.put("es", "Usuario");
        map.put("et", "Kasutaja");
        map.put("eu", "Lankide");
        map.put("ext", "Usuario");
        map.put("fa", "کاربر");
        map.put("ff", "Utilisateur");
        map.put("fi", "Käyttäjä");
        map.put("fiu-vro", "Pruukja");
        map.put("fj", "User");
        map.put("fo", "Brúkari");
        map.put("fr", "Utilisateur");
        map.put("frp", "Utilisator");
        map.put("frr", "Benutzer");
        map.put("fur", "Utent");
        map.put("fy", "Meidogger");
        map.put("ga", "Úsáideoir");
        map.put("gag", "Kullanıcı");
        map.put("gan", "用戶");
        map.put("gcr", "Itilizatò");
        map.put("gd", "Cleachdaiche");
        map.put("gl", "Usuario");
        map.put("glk", "کارگير");
        map.put("gn", "Puruhára");
        map.put("gom", "वापरपी");
        map.put("gor", "Ta ohu'uwo");
        map.put("got", "𐌽𐌹𐌿𐍄𐌰𐌽𐌳𐍃");
        map.put("gu", "સભ્ય");
        map.put("gv", "Ymmydeyr");
        map.put("ha", "User");
        map.put("hak", "用戶");
        map.put("haw", "Mea hoʻohana");
        map.put("he", "משתמש");
        map.put("hi", "सदस्य");
        map.put("hif", "sadasya");
        map.put("hr", "Suradnik");
        map.put("hsb", "Wužiwar");
        map.put("ht", "Itilizatè");
        map.put("hu", "Szerkesztő");
        map.put("hy", "Մասնակից");
        map.put("hyw", "Մասնակից");
        map.put("ia", "Usator");
        map.put("id", "Pengguna");
        map.put("ie", "Usator");
        map.put("ig", "Ọbanife");
        map.put("ik", "User");
        map.put("ilo", "Agar-aramat");
        map.put("inh", "Доакъашхо");
        map.put("io", "Uzanto");
        map.put("is", "Notandi");
        map.put("it", "Utente");
        map.put("iu", "User");
        map.put("ja", "利用者");
        map.put("jam", "User");
        map.put("jbo", "pilno");
        map.put("jv", "Naraguna");
        map.put("ka", "მომხმარებელი");
        map.put("kaa", "Paydalanıwshı");
        map.put("kab", "Amseqdac");
        map.put("kbd", "ЦӀыхухэт");
        map.put("kbp", "Utilisateur");
        map.put("kg", "Kisadi");
        map.put("ki", "User");
        map.put("kk", "Қатысушы");
        map.put("kl", "Atuisoq");
        map.put("km", "អ្នកប្រើប្រាស់");
        map.put("kn", "ಸದಸ್ಯ");
        map.put("ko", "사용자");
        map.put("koi", "Участник");
        map.put("krc", "Къошулуучу");
        map.put("ks", "رُکُن");
        map.put("ksh", "Metmaacher");
        map.put("ku", "Bikarhêner");
        map.put("kv", "Пырысь");
        map.put("kw", "Devnydhyer");
        map.put("ky", "Колдонуучу");
        map.put("la", "Usor");
        map.put("lad", "Usador");
        map.put("lb", "Benotzer");
        map.put("lbe", "Гьуртту хьума");
        map.put("lez", "Уртах");
        map.put("lfn", "Usor");
        map.put("lg", "User");
        map.put("li", "Gebroeker");
        map.put("lij", "Utente");
        map.put("lld", "Utente");
        map.put("lmo", "Druvadur");
        map.put("ln", "Utilisateur");
        map.put("lo", "ຜູ້ໃຊ້");
        map.put("lrc", "کاریار");
        map.put("lt", "Naudotojas");
        map.put("ltg", "Lītuotuojs");
        map.put("lv", "Dalībnieks");
        map.put("mai", "प्रयोगकर्ता");
        map.put("map-bms", "Naraguna");
        map.put("mdf", "Тиись");
        map.put("mg", "Mpikambana");
        map.put("mhr", "Пайдаланыше");
        map.put("mi", "User");
        map.put("min", "Pangguno");
        map.put("mk", "Корисник");
        map.put("ml", "ഉപയോക്താവ്");
        map.put("mn", "Хэрэглэгч");
        map.put("mnw", "ညးလွပ်");
        map.put("mr", "सदस्य");
        map.put("mrj", "Сирӹшӹ");
        map.put("ms", "Pengguna");
        map.put("mt", "Utent");
        map.put("mwl", "Outelizador(a)");
        map.put("my", "အသုံးပြုသူ");
        map.put("myv", "Теиця");
        map.put("mzn", "کارور");
        map.put("na", "User");
        map.put("nah", "Tlatequitiltilīlli");
        map.put("nap", "Utente");
        map.put("nds", "Bruker");
        map.put("nds-nl", "Gebruker");
        map.put("ne", "प्रयोगकर्ता");
        map.put("new", "छ्येलेमि");
        map.put("nl", "Gebruiker");
        map.put("nn", "Brukar");
        map.put("nb", "Bruker");
        map.put("nov", "User");
        map.put("nqo", "ߟߊߓߊ߯ߙߟߊ");
        map.put("nrm", "Utilisateur");
        map.put("nso", "Mošomi");
        map.put("nv", "Choyoołʼįįhí");
        map.put("ny", "User");
        map.put("oc", "Utilizaire");
        map.put("olo", "Käyttäi");
        map.put("om", "User");
        map.put("or", "ବ୍ୟବହାରକାରୀ");
        map.put("os", "Архайæг");
        map.put("pa", "ਵਰਤੋਂਕਾਰ");
        map.put("pag", "User");
        map.put("pam", "User");
        map.put("pap", "User");
        map.put("pcd", "Utilisateur");
        map.put("pdc", "Yuuser");
        map.put("pfl", "Middawaida");
        map.put("pi", "अवयव");
        map.put("pih", "User");
        map.put("pl", "Wikipedysta");
        map.put("pms", "Utent");
        map.put("pnb", "ورتنوالا");
        map.put("pnt", "Χρήστες");
        map.put("ps", "کارن");
        map.put("pt", "Usuário(a)");
        map.put("qu", "Ruraq");
        map.put("rm", "Utilisader");
        map.put("rmy", "Jeno");
        map.put("rn", "User");
        map.put("ro", "Utilizator");
        map.put("roa-rup", "Utilizator");
        map.put("roa-tara", "Utente");
        map.put("ru", "Участник");
        map.put("rue", "Хоснователь");
        map.put("rw", "User");
        map.put("sa", "सदस्यः");
        map.put("sah", "Кыттааччы");
        map.put("sat", "ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ");
        map.put("sc", "Usuàriu");
        map.put("scn", "Utenti");
        map.put("sco", "Uiser");
        map.put("sd", "واپرائيندڙ");
        map.put("se", "Geavaheaddji");
        map.put("sg", "Utilisateur");
        map.put("sh", "Korisnik");
        map.put("shn", "ၽူႈၸႂ်ႉတိုဝ်း");
        map.put("si", "පරිශීලක");
        map.put("simple", "User");
        map.put("sk", "Redaktor");
        map.put("sl", "Uporabnik");
        map.put("sm", "User");
        map.put("sn", "User");
        map.put("so", "User");
        map.put("sq", "Përdoruesi");
        map.put("sr", "Корисник");
        map.put("srn", "Masyin");
        map.put("ss", "User");
        map.put("st", "User");
        map.put("stq", "Benutser");
        map.put("su", "Pamaké");
        map.put("sv", "Användare");
        map.put("sw", "Mtumiaji");
        map.put("szl", "Używacz");
        map.put("szy", "misaungayay");
        map.put("ta", "பயனர்");
        map.put("tcy", "ಬಳಕೆದಾರೆ");
        map.put("te", "వాడుకరి");
        map.put("tet", "Uza-na'in");
        map.put("tg", "Корбар");
        map.put("th", "ผู้ใช้");
        map.put("ti", "ተጠቃሚ");
        map.put("tk", "Ulanyjy");
        map.put("tl", "Tagagamit");
        map.put("tn", "User");
        map.put("to", "User");
        map.put("tpi", "Yusa");
        map.put("tr", "Kullanıcı");
        map.put("ts", "User");
        map.put("tt", "Кулланучы");
        map.put("tum", "User");
        map.put("tw", "User");
        map.put("ty", "Utilisateur");
        map.put("tyv", "Aжыглакчы");
        map.put("udm", "Викиавтор");
        map.put("ug", "ئىشلەتكۈچى");
        map.put("uk", "Користувач");
        map.put("ur", "صارف");
        map.put("uz", "Foydalanuvchi");
        map.put("ve", "User");
        map.put("vec", "Utente");
        map.put("vep", "Kävutai");
        map.put("vi", "Thành viên");
        map.put("vls", "Gebruker");
        map.put("vo", "Geban");
        map.put("wa", "Uzeu");
        map.put("war", "Gumaramit");
        map.put("wo", "Jëfandikukat");
        map.put("wuu", "User");
        map.put("xal", "Демнч");
        map.put("xh", "User");
        map.put("xmf", "მომხმარებელი");
        map.put("yi", "באַניצער");
        map.put("yo", "Oníṣe");
        map.put("za", "用户");
        map.put("zea", "Gebruker");
        map.put("zh", "User");
        map.put("zh-hans", "User");
        map.put("zh-hant", "User");
        map.put("zh-classical", "用戶");
        map.put("zh-min-nan", "Iōng-chiá");
        map.put("zh-yue", "User");
        map.put("zu", "User");
        map.put("test", "User");
        return map;
    }

    private UserAliasData() { }
}
