/* THIS IS AN AUTOMATICALLY GENERATED FILE
   IF YOU MODIFY THIS BY HAND BE PREPARED!
   TO HAVE YOUR CHANGES OVERWRITTEN */
package org.wikipedia.staticdata

import org.wikipedia.util.L10nUtil.getDesiredLanguageCode

object UserTalkAliasData {
    @JvmStatic
    fun valueFor(key: String): String {
        return dataMap[getDesiredLanguageCode(key)] ?: dataMap["en"]!!
    }

    private val dataMap = mapOf(
            "ab" to "Алахәыла ахцәажәара",
            "ace" to "Marit Ureuëng Ngui",
            "ady" to "User talk",
            "af" to "Gebruikerbespreking",
            "ak" to "Odwumanyɛni nkɔmmɔbea",
            "als" to "Benutzer Diskussion",
            "alt" to "Туружаачыны шӱӱжери",
            "am" to "አባል ውይይት",
            "ami" to "Kasasowal no midemakay",
            "an" to "Descusión usuario",
            "ang" to "Brūcendmōtung",
            "ar" to "نقاش المستخدم",
            "arc" to "ܡܡܠܠܐ ܕܡܦܠܚܢܐ",
            "ary" to "نقاش المستخدم",
            "arz" to "نقاش المستخدم",
            "as" to "সদস্য বাৰ্তা",
            "ast" to "Usuariu alderique",
            "atj" to "Ke ici aimihitonaniwok notcita iriniw",
            "av" to "ГӀахьалчиясул бахӀс",
            "avk" to "Favesikprilara",
            "awa" to "यूजर बातचीत",
            "ay" to "Usuario discusión",
            "az" to "İstifadəçi müzakirəsi",
            "azb" to "ایشلدن دانیشیغی",
            "ba" to "Ҡатнашыусы менән һөйләшеү",
            "ban" to "Pabligbagan Sang Anganggé",
            "bar" to "Nutza Dischkrian",
            "bat-smg" to "Nauduotuojė aptarėms",
            "bcl" to "Olay kan paragamit",
            "be" to "Размовы з удзельнікам",
            "be-x-old" to "Гутаркі ўдзельніка",
            "bg" to "Потребител беседа",
            "bh" to "प्रयोगकर्ता वार्ता",
            "bi" to "User talk",
            "bjn" to "Pamandiran Pamakai",
            "bm" to "Discussion utilisateur",
            "bn" to "ব্যবহারকারী আলাপ",
            "bo" to "User talk",
            "bpy" to "আতাকুরার য়্যারী",
            "br" to "Kaozeadenn Implijer",
            "bs" to "Razgovor s korisnikom",
            "bug" to "Pembicaraan Pengguna",
            "bxr" to "Хэрэглэгшые хэлэлсэхэ",
            "ca" to "Usuari Discussió",
            "cbk-zam" to "Usuario discusión",
            "cdo" to "用戶討論",
            "ce" to "Декъашхочун дийцаре",
            "ceb" to "Hisgot sa Gumagamit",
            "ch" to "Kombetsasion ni muna'sesetbi",
            "chr" to "User talk",
            "chy" to "User talk",
            "ckb" to "لێدوانی بەکارھێنەر",
            "co" to "Discussioni utente",
            "cr" to "User talk",
            "crh" to "Qullanıcı muzakeresi",
            "cs" to "Diskuse s wikipedistou",
            "csb" to "Diskùsëjô brëkòwnika",
            "cu" to "Польꙃєватєлꙗ бєсѣда",
            "cv" to "Хутшăнаканăн канашлу страници",
            "cy" to "Sgwrs Defnyddiwr",
            "da" to "Brugerdiskussion",
            "dag" to "Ŋun su yɛltɔɣa",
            "de" to "Benutzer Diskussion",
            "din" to "Jam kekë dulooi",
            "diq" to "Karber vaten",
            "dsb" to "Diskusija wužywarja",
            "dty" to "प्रयोगकर्ता कुरणि",
            "dv" to "މެމްބަރުގެ ވާހަކަ",
            "dz" to "User talk",
            "ee" to "User talk",
            "el" to "Συζήτηση χρήστη",
            "eml" to "Discussioni utente",
            "en" to "User talk",
            "eo" to "Uzanto-Diskuto",
            "es" to "Usuario discusión",
            "et" to "Kasutaja arutelu",
            "eu" to "Lankide eztabaida",
            "ext" to "Usuario caraba",
            "fa" to "بحث کاربر",
            "ff" to "Discussion utilisateur",
            "fi" to "Keskustelu käyttäjästä",
            "fiu-vro" to "Pruukja arotus",
            "fj" to "User talk",
            "fo" to "Brúkarakjak",
            "fr" to "Discussion utilisateur",
            "frp" to "Discussion utilisator",
            "frr" to "Benutzer Diskussion",
            "fur" to "Discussion utent",
            "fy" to "Meidogger oerlis",
            "ga" to "Plé úsáideora",
            "gag" to "Kullanıcı dartışma",
            "gan" to "用戶・談詑",
            "gcr" to "Diskisyon itilizatò",
            "gd" to "Deasbaireachd a' chleachdaiche",
            "gl" to "Conversa usuario",
            "glk" to "کارگيرˇ گب",
            "gn" to "Puruhára myangekõi",
            "gom" to "वापरपी चर्चा",
            "gor" to "Lo'iya ta ohu'uwo",
            "got" to "𐌽𐌹𐌿𐍄𐌰𐌽𐌳𐌹𐍃 𐌲𐌰𐍅𐌰𐌿𐍂𐌳𐌾𐌰",
            "gu" to "સભ્યની ચર્ચા",
            "gv" to "Resooney ymmydeyr",
            "ha" to "User talk",
            "hak" to "用戶討論",
            "haw" to "Kūkākūkā o mea hoʻohana",
            "he" to "שיחת משתמש",
            "hi" to "सदस्य वार्ता",
            "hif" to "sadasya ke baat",
            "hr" to "Razgovor sa suradnikom",
            "hsb" to "Diskusija z wužiwarjom",
            "ht" to "Diskisyon Itilizatè",
            "hu" to "Szerkesztővita",
            "hy" to "Մասնակցի քննարկում",
            "hyw" to "Մասնակցի քննարկում",
            "ia" to "Discussion Usator",
            "id" to "Pembicaraan Pengguna",
            "ie" to "Usator Discussion",
            "ig" to "Okwu ọbanife",
            "ik" to "User talk",
            "ilo" to "Agar-aramat tungtungan",
            "inh" to "Доакъашхочун дувцар",
            "io" to "Uzanto Debato",
            "is" to "Notandaspjall",
            "it" to "Discussioni utente",
            "iu" to "User talk",
            "ja" to "利用者‐会話",
            "jam" to "User talk",
            "jbo" to "casnu lo pilno",
            "jv" to "Parembugan Naraguna",
            "ka" to "მომხმარებლის განხილვა",
            "kaa" to "Paydalanıwshı sa'wbeti",
            "kab" to "Amyannan umsqedac",
            "kbd" to "ЦӀыхухэт тепсэлъэхьыгъуэ",
            "kbp" to "Discussion utilisateur",
            "kg" to "Disolo kisadi",
            "ki" to "User talk",
            "kk" to "Қатысушы талқылауы",
            "kl" to "Atuisup oqalliffia",
            "km" to "ការពិភាក្សារបស់អ្នកប្រើប្រាស់",
            "kn" to "ಸದಸ್ಯರ ಚರ್ಚೆಪುಟ",
            "ko" to "사용자토론",
            "koi" to "Обсуждение участника",
            "krc" to "Къошулуучуну сюзюу",
            "ks" to "رُکُن بَحَژ",
            "ksh" to "Metmaacher Klaaf",
            "ku" to "Gotûbêja bikarhêner",
            "kv" to "Пырыськӧд сёрнитанiн",
            "kw" to "Keskows Devnydhyer",
            "ky" to "Колдонуучунун баарлашуулары",
            "la" to "Disputatio Usoris",
            "lad" to "Messaje de Usador",
            "lb" to "Benotzer Diskussioun",
            "lbe" to "Гьуртту хьуминнал ихтилат",
            "lez" to "Уртахдин веревирд авун",
            "lfn" to "Usor Discute",
            "lg" to "User talk",
            "li" to "Euverlèk gebroeker",
            "lij" to "Discûscioîn ûtente",
            "lld" to "Discussioni utente",
            "lmo" to "Ciciarada Utent",
            "ln" to "Discussion utilisateur",
            "lo" to "ສົນທະນາຂອງຜູ້ໃຊ້",
            "lt" to "Naudotojo aptarimas",
            "ltg" to "Sprīža ap lītuotuoju",
            "lv" to "Dalībnieka diskusija",
            "mad" to "Pakanḍhâ'ânna pangangghuy",
            "mai" to "प्रयोगकर्ता वार्ता",
            "map-bms" to "Parembugan Naraguna",
            "mdf" to "Тиись корхнема",
            "mg" to "Dinika amin'ny mpikambana",
            "mhr" to "Пайдаланышын каҥашымашыже",
            "mi" to "User talk",
            "min" to "Rundiang Pangguno",
            "mk" to "Разговор со корисник",
            "ml" to "ഉപയോക്താവിന്റെ സംവാദം",
            "mn" to "Хэрэглэгчийн яриа",
            "mni" to "ꯁꯤꯖꯤꯟꯅꯔꯤꯕ ꯋꯥ ꯍꯥꯏꯐꯝ",
            "mnw" to "ညးလွပ် ဓရီုကျာ",
            "mr" to "सदस्य चर्चा",
            "mrj" to "Сирӹшӹм кӓнгӓшӹмӓш",
            "ms" to "Perbincangan pengguna",
            "mt" to "Diskussjoni utent",
            "mwl" to "Cumbersa outelizador(a)",
            "my" to "အသုံးပြုသူ ဆွေးနွေးချက်",
            "myv" to "Теицянь кортамось",
            "mzn" to "کارور گپ",
            "na" to "User talk",
            "nah" to "Tlatequitiltilīlli tēixnāmiquiliztli",
            "nap" to "Utente chiàcchiera",
            "nds" to "Bruker Diskuschoon",
            "nds-nl" to "Overleg gebruker",
            "ne" to "प्रयोगकर्ता वार्ता",
            "new" to "छ्येलेमि खँलाबँला",
            "nia" to "Huhuo zangoguna",
            "nl" to "Overleg gebruiker",
            "nn" to "Brukardiskusjon",
            "nb" to "Brukerdiskusjon",
            "nov" to "User talk",
            "nqo" to "ߟߊߓߊ߯ߙߟߊ ߟߊ߫ ߢߊߝߐߞߣߍ",
            "nrm" to "Discussion utilisateur",
            "nso" to "Boledišana le Mošomi",
            "nv" to "Choyoołʼįįhí bichʼįʼ yáshtiʼ",
            "ny" to "User talk",
            "oc" to "Discussion Utilizaire",
            "olo" to "Käyttäi pagin",
            "om" to "User talk",
            "or" to "ବ୍ୟବହାରକାରୀଙ୍କ ଆଲୋଚନା",
            "os" to "Архайæджы ныхас",
            "pa" to "ਵਰਤੋਂਕਾਰ ਗੱਲ-ਬਾਤ",
            "pag" to "User talk",
            "pam" to "User talk",
            "pap" to "User talk",
            "pcd" to "Discussion utilisateur",
            "pdc" to "Yuuser Dischbedutt",
            "pfl" to "Middawaida Dischbediere",
            "pi" to "अवयव सम्भासित",
            "pih" to "User talk",
            "pl" to "Dyskusja wikipedysty",
            "pms" to "Ciaciarade",
            "pnb" to "ورتن گل بات",
            "pnt" to "Καλάτσεμαν χρήστε",
            "ps" to "د کارن خبرې اترې",
            "pt" to "Usuário(a) Discussão",
            "pwn" to "kipakamanguanguaq kakaljavaran",
            "qu" to "Ruraq rimanakuy",
            "rm" to "Utilisader discussiun",
            "rmy" to "Jeno vakyarimata",
            "rn" to "User talk",
            "ro" to "Discuție Utilizator",
            "roa-rup" to "Discuție Utilizator",
            "roa-tara" to "Discussioni utente",
            "ru" to "Обсуждение участника",
            "rue" to "Діскузія з хоснователём",
            "rw" to "Ibiganiro by'umukoresha",
            "sa" to "सदस्यसम्भाषणम्",
            "sah" to "Кыттааччы ырытыыта",
            "sat" to "ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ ᱜᱟᱞᱢᱟᱨᱟᱣ",
            "sc" to "Cuntierra usuàriu",
            "scn" to "Discussioni utenti",
            "sco" to "Uiser collogue",
            "sd" to "واپرائيندڙ بحث",
            "se" to "Geavaheaddjeságastallan",
            "sg" to "Discussion utilisateur",
            "sh" to "Razgovor sa korisnikom",
            "shi" to "Amsawal n usmras",
            "shn" to "ဢုပ်ႇၵုမ် ၽူႈၸႂ်ႉတိုဝ်း",
            "si" to "පරිශීලක සාකච්ඡාව",
            "simple" to "User talk",
            "sk" to "Diskusia s redaktorom",
            "skr" to "ورتݨ آلے دی ڳالھ مہاڑ",
            "sl" to "Uporabniški pogovor",
            "sm" to "User talk",
            "smn" to "Savâstâllâm kevttest",
            "sn" to "User talk",
            "so" to "User talk",
            "sq" to "Përdoruesi diskutim",
            "sr" to "Разговор са корисником",
            "srn" to "Taki fu masyin",
            "ss" to "User talk",
            "st" to "User talk",
            "stq" to "Benutser Diskussion",
            "su" to "Obrolan pamaké",
            "sv" to "Användardiskussion",
            "sw" to "Majadiliano ya mtumiaji",
            "szl" to "Dyskusyjo używacza",
            "szy" to "pisubelidan tu kamu ni misaungayay sapimatatengil",
            "ta" to "பயனர் பேச்சு",
            "tay" to "spkayal cinzyuwaw",
            "tcy" to "ಬಳಕೆದಾರೆ ಪಾತೆರ",
            "te" to "వాడుకరి చర్చ",
            "tet" to "Diskusaun Uza-na'in",
            "tg" to "Баҳси корбар",
            "th" to "คุยกับผู้ใช้",
            "ti" to "ምይይጥ ተጠቃሚ",
            "tk" to "Ulanyjy çekişme",
            "tl" to "Usapang tagagamit",
            "tn" to "User talk",
            "to" to "User talk",
            "tpi" to "Toktok bilong yusa",
            "tr" to "Kullanıcı mesaj",
            "trv" to "Pprngagun empduuy",
            "ts" to "User talk",
            "tt" to "Кулланучы бәхәсе",
            "tum" to "User talk",
            "tw" to "User talk",
            "ty" to "Discussion utilisateur",
            "tyv" to "Ажыглакчы чугаа",
            "udm" to "Викиавтор сярысь вераськон",
            "ug" to "ئىشلەتكۈچى مۇنازىرىسى",
            "uk" to "Обговорення користувача",
            "ur" to "تبادلۂ خیال صارف",
            "uz" to "Foydalanuvchi munozarasi",
            "ve" to "User talk",
            "vec" to "Discusion Utensa",
            "vep" to "Lodu kävutajas",
            "vi" to "Thảo luận Thành viên",
            "vls" to "Discuusje gebruker",
            "vo" to "Gebanibespik",
            "wa" to "Uzeu copene",
            "war" to "Hiruhimangaw hiton gumaramit",
            "wo" to "Waxtaani jëfandikukat",
            "wuu" to "User talk",
            "xal" to "Демнчна туск меткән",
            "xh" to "User talk",
            "xmf" to "მომხმარებლის განხილვა",
            "yi" to "באַניצער רעדן",
            "yo" to "Ọ̀rọ̀ oníṣe",
            "za" to "用户讨论",
            "zea" to "Overleg gebruker",
            "zh" to "User talk",
            "zh-hans" to "User talk",
            "zh-hant" to "User talk",
            "zh-classical" to "用戶討論",
            "zh-min-nan" to "Iōng-chiá thó-lūn",
            "zh-yue" to "User talk",
            "zu" to "User talk",
            "test" to "User talk",
    )
}
