/* THIS IS AN AUTOMATICALLY GENERATED FILE
   IF YOU MODIFY THIS BY HAND BE PREPARED!
   TO HAVE YOUR CHANGES OVERWRITTEN */
package org.wikipedia.staticdata;

import androidx.annotation.NonNull;

import org.wikipedia.util.L10nUtil;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public final class UserTalkAliasData {
    @NonNull private static final Map<String, String> DATA_MAP = Collections.unmodifiableMap(newMap());

    @NonNull public static String valueFor(String key) {
        key = L10nUtil.getDesiredLanguageCode(key);
        if (DATA_MAP.containsKey(key)) {
            return DATA_MAP.get(key);
        }
        return DATA_MAP.get("en");
    }

    @SuppressWarnings({"checkstyle:methodlength", "SpellCheckingInspection"})
    private static Map<String, String> newMap() {
        final int size = 307;
        Map<String, String> map = new HashMap<>(size);
        map.put("pag", "User talk");
        map.put("pam", "User talk");
        map.put("os", "Архайæджы ныхас");
        map.put("pa", "ਵਰਤੋਂਕਾਰ ਗੱਲ-ਬਾਤ");
        map.put("om", "User talk");
        map.put("or", "ବ୍ୟବହାରକାରୀଙ୍କ ଆଲୋଚନା");
        map.put("oc", "Discussion Utilizaire");
        map.put("olo", "Käyttäi pagin");
        map.put("ln", "Discussion utilisateur");
        map.put("st", "User talk");
        map.put("stq", "Benutser Diskussion");
        map.put("pap", "User talk");
        map.put("pcd", "Discussion utilisateur");
        map.put("kaa", "Paydalanıwshı sa'wbeti");
        map.put("ka", "მომხმარებლის განხილვა");
        map.put("jv", "Parembugan Naraguna");
        map.put("jbo", "casnu lo pilno");
        map.put("kg", "Disolo kisadi");
        map.put("kbp", "Discussion utilisateur");
        map.put("kbd", "ЦӀыхухэт тепсэлъэхьыгъуэ");
        map.put("kab", "Amyannan umsqedac");
        map.put("ki", "User talk");
        map.put("lo", "ສົນທະນາຂອງຜູ້ໃຊ້");
        map.put("ban", "Pabligbagan Sang Anganggé");
        map.put("bar", "Nutza Dischkrian");
        map.put("bat-smg", "Nauduotuojė aptarėms");
        map.put("bcl", "Olay kan paragamit");
        map.put("ay", "Usuario discusión");
        map.put("az", "İstifadəçi müzakirəsi");
        map.put("azb", "ایشلدن دانیشیغی");
        map.put("ba", "Ҡатнашыусы менән һөйләшеү");
        map.put("lg", "User talk");
        map.put("be", "Размовы з удзельнікам");
        map.put("li", "Euverlèk gebroeker");
        map.put("tyv", "Aжыглакчы чугаа");
        map.put("af", "Gebruikerbespreking");
        map.put("to", "User talk");
        map.put("an", "Descusión usuario");
        map.put("tr", "Kullanıcı mesaj");
        map.put("lld", "Discussioni utente");
        map.put("tt", "Кулланучы бәхәсе");
        map.put("ts", "User talk");
        map.put("tw", "User talk");
        map.put("tum", "User talk");
        map.put("ig", "Okwu ọbanife");
        map.put("ta", "பயனர் பேச்சு");
        map.put("sn", "User talk");
        map.put("ik", "User talk");
        map.put("ilo", "Agar-aramat tungtungan");
        map.put("inh", "Доакъашхочун дувцар");
        map.put("io", "Uzanto Debato");
        map.put("is", "Notandaspjall");
        map.put("it", "Discussioni utente");
        map.put("iu", "User talk");
        map.put("ja", "利用者‐会話");
        map.put("jam", "User talk");
        map.put("szl", "Dyskusyjo używacza");
        map.put("sw", "Majadiliano ya mtumiaji");
        map.put("lrc", "چأک چئنە کاریار");
        map.put("ie", "Usator Discussion");
        map.put("cv", "Хутшăнаканăн канашлу страници");
        map.put("cu", "Польꙃєватєлꙗ бєсѣда");
        map.put("crh", "Qullanıcı muzakeresi");
        map.put("cr", "User talk");
        map.put("csb", "Diskùsëjô brëkòwnika");
        map.put("cs", "Diskuse s wikipedistou");
        map.put("chy", "User talk");
        map.put("chr", "User talk");
        map.put("co", "Discussioni utente");
        map.put("ckb", "لێدوانی بەکارھێنەر");
        map.put("so", "User talk");
        map.put("zea", "Overleg gebruker");
        map.put("vi", "Thảo luận Thành viên");
        map.put("vls", "Discuusje gebruker");
        map.put("vec", "Discusion Utensa");
        map.put("vep", "Lodu kävutajas");
        map.put("uz", "Foydalanuvchi munozarasi");
        map.put("ve", "User talk");
        map.put("uk", "Обговорення користувача");
        map.put("ur", "تبادلۂ خیال صارف");
        map.put("udm", "Викиавтор сярысь вераськон");
        map.put("ug", "ئىشلەتكۈچى مۇنازىرىسى");
        map.put("lmo", "Ciciarada Druvadur");
        map.put("nl", "Overleg gebruiker");
        map.put("new", "छ्येलेमि खँलाबँला");
        map.put("mk", "Разговор со корисник");
        map.put("nap", "Utente chiàcchiera");
        map.put("nah", "Tlatequitiltilīlli tēixnāmiquiliztli");
        map.put("nds-nl", "Overleg gebruker");
        map.put("min", "Rundiang Pangguno");
        map.put("myv", "Теицянь кортамось");
        map.put("my", "အသုံးပြုသူ ဆွေးနွေးချက်");
        map.put("na", "User talk");
        map.put("mzn", "کارور گپ");
        map.put("hyw", "Մասնակցի քննարկում");
        map.put("fy", "Meidogger oerlis");
        map.put("ga", "Plé úsáideora");
        map.put("ht", "Diskisyon Itilizatè");
        map.put("hsb", "Diskusija z wužiwarjom");
        map.put("hy", "Մասնակցի քննարկում");
        map.put("hu", "Szerkesztővita");
        map.put("fj", "User talk");
        map.put("fo", "Brúkarakjak");
        map.put("fi", "Keskustelu käyttäjästä");
        map.put("fiu-vro", "Pruukja arotus");
        map.put("frr", "Benutzer Diskussion");
        map.put("fur", "Discussion utent");
        map.put("fr", "Discussion utilisateur");
        map.put("frp", "Discussion utilisator");
        map.put("wuu", "User talk");
        map.put("ne", "प्रयोगकर्ता वार्ता");
        map.put("sm", "User talk");
        map.put("nrm", "Discussion utilisateur");
        map.put("pnb", "ورتن گل بات");
        map.put("smn", "Savâstâllâm kevttest");
        map.put("ady", "User talk");
        map.put("mi", "User talk");
        map.put("sk", "Diskusia s redaktorom");
        map.put("am", "አባል ውይይት");
        map.put("se", "Geavaheaddjeságastallan");
        map.put("te", "వాడుకరి చర్చ");
        map.put("sl", "Uporabniški pogovor");
        map.put("yi", "באַניצער רעדן");
        map.put("yo", "Ọ̀rọ̀ oníṣe");
        map.put("vo", "Gebanibespik");
        map.put("wa", "Uzeu copene");
        map.put("war", "Hiruhimangaw hiton gumaramit");
        map.put("wo", "Waxtaani jëfandikukat");
        map.put("pms", "Ciaciarade");
        map.put("xal", "Демнчна туск меткән");
        map.put("xh", "User talk");
        map.put("xmf", "მომხმარებლის განხილვა");
        map.put("sco", "Uiser collogue");
        map.put("scn", "Discussioni utenti");
        map.put("hr", "Razgovor sa suradnikom");
        map.put("sah", "Кыттааччы ырытыыта");
        map.put("sa", "सदस्यसम्भाषणम्");
        map.put("sc", "Cuntierra usuàriu");
        map.put("sat", "ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ ᱜᱟᱞᱢᱟᱨᱟᱣ");
        map.put("ha", "User talk");
        map.put("hak", "用戶討論");
        map.put("gu", "સભ્યની ચર્ચા");
        map.put("gv", "Resooney ymmydeyr");
        map.put("hi", "सदस्य वार्ता");
        map.put("hif", "sadasya ke baat");
        map.put("haw", "Kūkākūkā o mea hoʻohana");
        map.put("he", "שיחת משתמש");
        map.put("br", "Kaozeadenn Implijer");
        map.put("bpy", "আতাকুরার য়্যারী");
        map.put("bi", "User talk");
        map.put("bh", "प्रयोगकर्ता वार्ता");
        map.put("bg", "Потребител беседа");
        map.put("be-x-old", "Гутаркі ўдзельніка");
        map.put("bo", "User talk");
        map.put("bn", "ব্যবহারকারী আলাপ");
        map.put("bm", "Discussion utilisateur");
        map.put("bjn", "Pamandiran Pamakai");
        map.put("sd", "واپرائيندڙ بحث");
        map.put("tpi", "Toktok bilong yusa");
        map.put("si", "පරිශීලක සාකච්ඡාව");
        map.put("nqo", "ߟߊߓߊ߯ߙߟߊ ߟߊ߫ ߢߊߝߐߞߣߍ");
        map.put("pih", "User talk");
        map.put("mhr", "Пайдаланышын каҥашымашыже");
        map.put("cy", "Sgwrs Defnyddiwr");
        map.put("da", "Brugerdiskussion");
        map.put("de", "Benutzer Diskussion");
        map.put("din", "Jam kekë dulooi");
        map.put("diq", "Karber vaten");
        map.put("dsb", "Diskusija wužywarja");
        map.put("dty", "प्रयोगकर्ता कुरणि");
        map.put("dv", "މެމްބަރުގެ ވާހަކަ");
        map.put("dz", "User talk");
        map.put("ee", "User talk");
        map.put("mg", "Dinika amin'ny mpikambana");
        map.put("mdf", "Тиись корхнема");
        map.put("map-bms", "Parembugan Naraguna");
        map.put("mai", "प्रयोगकर्ता वार्ता");
        map.put("lv", "Dalībnieka diskusija");
        map.put("nb", "Brukerdiskusjon");
        map.put("pi", "अवयव सम्भासित");
        map.put("ty", "Discussion utilisateur");
        map.put("mn", "Хэрэглэгчийн яриа");
        map.put("simple", "User talk");
        map.put("sg", "Discussion utilisateur");
        map.put("mnw", "ညးလွပ် ဓရီုကျာ");
        map.put("ml", "ഉപയോക്താവിന്റെ സംവാദം");
        map.put("ace", "Marit Ureuëng Ngui");
        map.put("lij", "Discûscioîn ûtente");
        map.put("mt", "Diskussjoni utent");
        map.put("mr", "सदस्य चर्चा");
        map.put("als", "Benutzer Diskussion");
        map.put("pdc", "Yuuser Dischbedutt");
        map.put("ms", "Perbincangan pengguna");
        map.put("mwl", "Cumbersa outelizador(a)");
        map.put("za", "用户讨论");
        map.put("nn", "Brukardiskusjon");
        map.put("zh", "User talk");
        map.put("zh-hans", "User talk");
        map.put("zh-hant", "User talk");
        map.put("nds", "Bruker Diskuschoon");
        map.put("pfl", "Middawaida Dischbediere");
        map.put("zu", "User talk");
        map.put("mrj", "Сирӹшӹм кӓнгӓшӹмӓш");
        map.put("zh-min-nan", "Iōng-chiá thó-lūn");
        map.put("zh-yue", "User talk");
        map.put("got", "𐌽𐌹𐌿𐍄𐌰𐌽𐌳𐌹𐍃 𐌲𐌰𐍅𐌰𐌿𐍂𐌳𐌾𐌰");
        map.put("gor", "Lo'iya ta ohu'owo");
        map.put("lt", "Naudotojo aptarimas");
        map.put("ltg", "Sprīža ap lītuotuoju");
        map.put("pt", "Usuário(a) Discussão");
        map.put("ps", "د کارن خبرې اترې");
        map.put("gan", "用戶・談詑");
        map.put("gag", "Kullanıcı dartışma");
        map.put("gd", "Deasbaireachd a' chleachdaiche");
        map.put("gcr", "Diskisyon itilizatò");
        map.put("glk", "کارگيرˇ گب");
        map.put("gl", "Conversa usuario");
        map.put("gom", "वापरपी चर्चा");
        map.put("gn", "Puruhára myangekõi");
        map.put("arc", "ܡܡܠܠܐ ܕܡܦܠܚܢܐ");
        map.put("ar", "نقاش المستخدم");
        map.put("arz", "نقاش المستخدم");
        map.put("ary", "نقاش المستخدم");
        map.put("ast", "Usuariu alderique");
        map.put("as", "সদস্য বাৰ্তা");
        map.put("av", "ГӀахьалчиясул бахӀс");
        map.put("atj", "Ke ici aimihitonaniwok notcita iriniw");
        map.put("awa", "यूजर बातचीत");
        map.put("avk", "Favesikprilara");
        map.put("zh-classical", "用戶討論");
        map.put("id", "Pembicaraan Pengguna");
        map.put("shn", "ဢုပ်ႇၵုမ် ၽူႈၸႂ်ႉတိုဝ်း");
        map.put("ia", "Discussion Usator");
        map.put("tet", "Diskusaun Uza-na'in");
        map.put("nov", "User talk");
        map.put("tg", "Баҳси корбар");
        map.put("kv", "Пырыськӧд сёрнитанiн");
        map.put("ku", "Gotûbêja bikarhêner");
        map.put("ky", "Колдонуучунун баарлашуулары");
        map.put("kw", "Keskows Devnydhyer");
        map.put("lad", "Messaje de Usador");
        map.put("la", "Disputatio Usoris");
        map.put("lbe", "Гьуртту хьуминнал ихтилат");
        map.put("lb", "Benotzer Diskussioun");
        map.put("lfn", "Usor Discute");
        map.put("lez", "Уртахдин веревирд авун");
        map.put("ti", "ተጠቃሚ ምይይጥ");
        map.put("ro", "Discuție Utilizator");
        map.put("rue", "Діскузія з хоснователём");
        map.put("rw", "User talk");
        map.put("tl", "Usapang tagagamit");
        map.put("nso", "Boledišana le Mošomi");
        map.put("roa-rup", "Discuție Utilizator");
        map.put("roa-tara", "Discussioni utente");
        map.put("ru", "Обсуждение участника");
        map.put("qu", "Ruraq rimanakuy");
        map.put("rm", "Utilisader discussiun");
        map.put("rmy", "Jeno vakyarimata");
        map.put("rn", "User talk");
        map.put("pl", "Dyskusja wikipedysty");
        map.put("tn", "User talk");
        map.put("ch", "Kombetsasion ni muna'sesetbi");
        map.put("ce", "Декъашхочун дийцаре");
        map.put("ceb", "Hisgot sa Gumagamit");
        map.put("cbk-zam", "Usuario discusión");
        map.put("cdo", "用戶討論");
        map.put("bxr", "Хэрэглэгшые хэлэлсэхэ");
        map.put("ca", "Usuari Discussió");
        map.put("bs", "Razgovor s korisnikom");
        map.put("bug", "Pembicaraan Pengguna");
        map.put("ab", "Алахәыла ахцәажәара");
        map.put("ak", "Odwumanyɛni nkɔmmɔbea");
        map.put("ang", "Brūcendmōtung");
        map.put("tcy", "ಬಳಕೆದಾರೆ ಪಾತೆರ");
        map.put("krc", "Къошулуучуну сюзюу");
        map.put("ko", "사용자토론");
        map.put("koi", "Обсуждение участника");
        map.put("km", "ការពិភាក្សារបស់អ្នកប្រើប្រាស់");
        map.put("kn", "ಸದಸ್ಯರ ಚರ್ಚೆಪುಟ");
        map.put("kk", "Қатысушы талқылауы");
        map.put("kl", "Atuisup oqalliffia");
        map.put("ny", "User talk");
        map.put("nv", "Choyoołʼįįhí bichʼįʼ yáshtiʼ");
        map.put("ks", "رُکُن بَحَژ");
        map.put("ksh", "Metmaacher Klaaf");
        map.put("ext", "Usuario caraba");
        map.put("eu", "Lankide eztabaida");
        map.put("et", "Kasutaja arutelu");
        map.put("es", "Usuario discusión");
        map.put("eo", "Uzanto-Diskuto");
        map.put("en", "User talk");
        map.put("eml", "Discussioni utente");
        map.put("el", "Συζήτηση χρήστη");
        map.put("tk", "Ulanyjy çekişme");
        map.put("ff", "Discussion utilisateur");
        map.put("fa", "بحث کاربر");
        map.put("ss", "User talk");
        map.put("sh", "Razgovor sa korisnikom");
        map.put("srn", "Taki fu masyin");
        map.put("pnt", "Καλάτσεμαν χρήστε");
        map.put("sr", "Разговор са корисником");
        map.put("szy", "pisubelidan tu kamu ni misaungayay sapimatatengil");
        map.put("sq", "Përdoruesi diskutim");
        map.put("th", "คุยกับผู้ใช้");
        map.put("sv", "Användardiskussion");
        map.put("su", "Obrolan pamaké");
        map.put("test", "User talk");
        return map;
    }

    private UserTalkAliasData() { }
}
