#!/usr/bin/env bash
set -euo pipefail

# Optionally pass an Android SDK location as an argument:
# $ apps-android-wikipedia-publish /srv/jenkins-workspace/tools/android-sdk
if [ ! $# -eq 0 ]; then
  echo "org.gradle.jvmargs=-Xmx1536M" >> gradle.properties
  export ANDROID_HOME="${1}"
  scripts/jenkins_sdk_setup "${ANDROID_HOME}"
else
  export ANDROID_HOME="$PWD/.sdk"
fi

declare START_TIME="$(date +"%Y-%m-%dT%H:%M:%S.%N")"
./gradlew -q clean assembleAlphaRelease
echo "{\"commit_hash\": \"$GIT_COMMIT\", \"completed_on\": \"$START_TIME\"}" > meta.json
