
if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis"
  git remote add release "https://${GH_TOKEN}@github.com/wikimedia/apps-android-wikipedia.git"
  git push -d release latest
  git tag -d latest
  git tag -a "latest" -m "[Autogenerated] This is the latest alpha version of the app."
  git push release --tags
  md5sum app/build/outputs/apk/alpha/release/app-alpha-universal-release.apk > app/build/outputs/apk/alpha/release/md5.txt
fi
