
if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis"

  git push -d origin latest
  git tag -d latest
  git tag -a "latest" -m "[Autogenerated] This is the latest alpha version of the app."
  git push origin --tags
  git fetch origin
fi
