package org.wikipedia.yearinreview

data class YearInReviewModel(
    val enReadingTimeSpent: Long,
    val enPopularArticles: List<String>,
    val enEditsCount: Long,
    val enBytesAddedCount: Long,
    val availableLanguages: Int,
    val globalTotalArticles: Long,
    val globalEditsCount: Long,
    val articlesViewedTimes: Long,
    val articlesSavedTimes: Long,
    val localReadingTimeSpent: Long,
    val localReadingArticles: Int,
    val localReadingRank: String, // TODO: TBD: top 50% or pure numbers,
    val localSavedArticles: List<String>,
    val localTopVisitedArticles: List<String>,
    val favoriteTimeToRead: String,
    val favoriteDayToRead: String,
    val favoriteMonthDidMostReading: String,
    val topCategories: List<String>,
    val closestLocation: Pair<Double, Double>,
    val closestArticles: List<String>,
    val userEditsCount: Long,
    val userEditsViewedTimes: Long,
    val appsEditsCount: Long,
    val editsPerMinute: Long,
)
